sudo: false

language: node_js

node_js:
  - "stable"

install:
  - npm ci

script:
  - npm run build

notifications:
  email: false

deploy:
  provider: script
  script: npm run build
  on:
    branch: feature/FDA-88